version: "3.9"

services:
  strapi:
    build: .
    image: strapi-app
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    volumes:
      - ./public/uploads:/app/public/uploads

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - strapi
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/uploads:/app/public/uploads

volumes:
  pgdata:

